### ISSUE TITLE
Cannot parse the file list.

### ISSUE THREAD

**Issue by SacalmM** [pyscsd/steamCloudSaveDownloader#11] opened 2024-11-07 09:20 UTC
I'm using the docker container. There's no way to get it to download anything, I always get the same error. I've seen a couple of similar issues that were resolved by simply updating the version. I'm using the latest available.

2024-11-07 09:14:16 [INFO] CWD: /
2024-11-07 09:14:16 [INFO] Files will be saved to '/data'
2024-11-07 09:14:16 [INFO] Refreshing session
2024-11-07 09:14:17 [INFO] Getting Game Save List
2024-11-07 09:14:17 [INFO] Random sleep for 5 seconds
2024-11-07 09:14:26 [INFO] (1/407) Processing Half-Life 2
2024-11-07 09:14:26 [INFO] Random sleep for 3 seconds
2024-11-07 09:14:29 [ERROR] Cannot parse the file list. It seems like Steam has update the webpage. Please update to the latest version or notify the author.
2024-11-07 09:14:29 [INFO] Retrying in 5 seconds
2024-11-07 09:14:29 [INFO] Random sleep for 5 seconds
2024-11-07 09:14:34 [ERROR] Cannot parse the file list. It seems like Steam has update the webpage. Please update to the latest version or notify the author.
2024-11-07 09:14:34 [INFO] Retrying in 5 seconds
2024-11-07 09:14:34 [INFO] Random sleep for 5 seconds
2024-11-07 09:14:40 [ERROR] Cannot parse the file list. It seems like Steam has update the webpage. Please update to the latest version or notify the author.
2024-11-07 09:14:40 [INFO] Retrying in 3 seconds
2024-11-07 09:14:40 [ERROR] Maximum attempt reached. Aborting
2024-11-07 09:14:40 [WARNING] Notifier not working as intended. Exception:
2024-11-07 09:14:40 [WARNING] Expecting value: line 1 column 1 (char 0)2024-11-07 09:14:40 [ERROR] Cannot parse the file list. It seems like Steam has update the webpage. Please update to the latest version or notify the author.

**Comment by hhhhhojeihsu** [comment] 2024-11-07 09:37
Hi SacalmM

Could you upload the html file for the link to the storage for [Half-Life 2](https://store.steampowered.com/account/remotestorageapp/?appid=220&l=english)? You can remove the private information (steamID, link to your save file etc.) if you want.

This would help me to understand what goes wrong in the process. Thanks.

**Comment by SacalmM** [comment] 2024-11-07 09:45
Yes, np. Thanks for you time and help!

![Screenshot_20241107_094232_Steam](https://github.com/user-attachments/assets/1221300a-3929-49f8-8134-ada5f9fb3ae3)

**Comment by SacalmM** [comment] 2024-11-07 10:30
I think you asking for a .zip, but I don't know how to get it ^^

**Comment by hhhhhojeihsu** [comment] 2024-11-07 10:41
Yes please save as html file instead 

> You can save it as webpage with Chrome Save As by pressing Ctrl + S on keyboard on windows. And choose HTML Only


https://store.steampowered.com/account/remotestorageapp/?appid=220&l=english

Also please make sure `&l=english` is presented at the end of url. This should override the language to English. As the program scraps the page based on English. Thanks.

**Comment by SacalmM** [comment] 2024-11-07 11:05
There you go. Thanks!

[Steam Cloud.zip](https://github.com/user-attachments/files/17660396/Steam.Cloud.zip)

**Comment by SacalmM** [comment] 2024-11-07 11:39
Update: I change de lenguage tonenglish and now is working well. Then, I need to keep steam in english?

**Comment by hhhhhojeihsu** [comment] 2024-11-07 14:38
Thanks for the information. I took a look into the file, it should work as intended. However, I encountered the same error message when I override my Steam language to non-English.

You can set the language to English as a workaround for now. I'll try to fix this in the meantime.

**Comment by hhhhhojeihsu** [comment] 2024-11-07 15:25
So it turns out that the language specifier is set incorrectly in 388bcfa without noticing it for 3 months. Should be fixed in 43452e6 and available as [v0.0.77](https://github.com/pyscsd/steamCloudSaveDownloader/releases/tag/v0.0.77).

Please pull the latest image on docker hub and try it again after rollback your steam language to native one instead of English.

Thanks for the report.

**Comment by SacalmM** [comment] 2024-11-07 16:22
Working with m Spanish language! Thank you very much for your time and work. Take care mate

**Closed** 2024-11-08 00:01 UTC
Labels: bug
