### ISSUE TITLE
Trouble with Docker image, not honoring "save_dir = /data" when run by scheduler

### ISSUE THREAD

**Issue by sofauxboho** [pyscsd/steamCloudSaveDownloader#4] opened 2024-03-01 00:45 UTC
Having a weird issue with the Docker image of scsd on Unraid.

I installed it per instructions on the main page. When run with:
`docker exec -it scsd scsd`
Everything works correctly and the operation succeeds. Saves are downloaded / updated. Log file in /data is updated.

When I open a console for that Docker image and simply run:
`scsd`
It also works correctly. Saves are downloaded / updated. Log file in /data is updated.

But when scsd is automatically run by the scheduler this is posted to the Discord webhook: 
![image](https://github.com/pyscsd/steamCloudSaveDownloader/assets/418438/9f936922-c37e-416f-9c4d-08a083e0640e)
No saves are downloaded, and the log file in /data is NOT updated.

After looking around for a while I found that there is also a scsd.log file at /user/data/scsd.log and that log contains the error message that was posted to the Discord webhook. So it seems that the scsd is using /user/data instead of /data but only when run by the scheduler.

As best I can tell, when I am running scsd manually it honors all parts of the .conf file, but when scsd is run by the scheduler it is honoring *some* of the .conf file (because the webhook notifier is working) but not the "save_dir = /data" section (because files are ending up in /user/data instead of /data).

Or perhaps something is forcing it to use ~/data instead of /data, but only when run by the scheduler?

Here is the conf file I'm using:
[scsd.conf.default.txt](https://github.com/pyscsd/steamCloudSaveDownloader/files/14454924/scsd.conf.default.txt)

**Comment by hhhhhojeihsu** [comment] 2024-03-01 14:43
It seems like this is an undocumented behavior. I guess your config file is named as `scsd.conf.default`. Which takes precedence after `scsd.conf` when run by the scheduler. You could take a look at the [simple shell script](https://github.com/pyscsd/steamCloudSaveDownloader/blob/master/docker/run.sh).

Please check if you have another file named `scsd.conf` within `/config`. Or, you could try to rename the config file to `scsd.conf` instead.

Please let me know if this solves the issue. I updated the documentation to reflect this. Thanks for the heads up.

**Comment by sofauxboho** [comment] 2024-03-01 17:20
The funny thing is that the Discord webhook configuration was done in the config file (which I had left named scsd.conf.default) and the Discord webhook was successfully firing to report "No session". But it wasn't finding the session because it was looking in ~/data (where there is nothing) instead of /data (where all the files created by running manually are) as configured in the *same* config file. Extremely weird.

I read the shell scripts and changed the name from scsd.conf.default to scsd.conf yesterday. I also made sure there was only one scsd.conf* file anywhere I could see. It did not seem to help. But I had also done a bunch of other meddling. I have now deleted everything and started from scratch. I currently have it running via "docker exec -it scsd-1 scsd" with no changes to the .conf file. It reported "2024-03-01 17:05:19 [INFO] Files will be saved to './data'". I have confirmed they are going to /data and not ~/data, and it seems to be working.

I'm going to let that complete and then wait for it to be run by the scheduler and see what output it generates (by manually checking the log). If that works I'll rename scsd.conf.default to scsd.conf and try making my changes (such as the Discord webhook) one at a time. 

Will report back either way.

**Comment by sofauxboho** [comment] 2024-03-01 19:31
Ok. After completely removing scsd from Docker, deleting all scsd related files, reinstalling from Docker Hub, making no config changes, and then running:
`docker exec -it scsd-1 scsd_auth sofauxboho`
and then:
'docker exec -it scsd-1 scsd'
That second command executes successfully when run manually and generates this log file in /data/scsd.log:
[slash-data-slash-scsd.log.txt](https://github.com/pyscsd/steamCloudSaveDownloader/files/14465126/slash-data-slash-scsd.log.txt)

I then waited for scsd to be run by the scheduler. When it was run by the scheduler the /data/scsd.log file was not updated. The /user/data/scsd.log file was updated instead, as follows: 
![image](https://github.com/pyscsd/steamCloudSaveDownloader/assets/418438/6f87644e-23b9-4d5c-b99c-bc073779ebcc)

Notes about this:

1. This is running via defaults with no configuration done. (Other than authenticating as above.)
2. The wrong data location is being used, /user/data instead of /data.
3. scsd does not work (I assume because it cannot find it's session data in that wrong folder).
4. Time is being reported in UTC not in my local timezone. 

If I then run "scsd" from the Docker console for that image scsd works normally and uses the correct /data directory, as shown here:
![image](https://github.com/pyscsd/steamCloudSaveDownloader/assets/418438/d80a6d6e-0ad6-46bb-9f8a-7d93682c59b4)

Even with the default config the Docker scsd uses /data when run manually and /user/data when run by the scheduler.

**Comment by hhhhhojeihsu** [comment] 2024-03-02 10:19
Appreciate the detailed comments and procedure. It makes the process significantly easier.

So the `scsd.conf.default` is created by the shell script (`/root/entry.sh`) on first startup. And it specified the old and wrong section name. Which should be `[General]` instead of `[Required]`. It was changed during the development and I forgot to change the shell script. This explains the Discord event is fired but the save directory is wrong. I will add a warning messages if additional sections is written within the config file.

This has been fixed in [v0.0.70]( https://github.com/pyscsd/steamCloudSaveDownloader/releases/tag/v0.0.70). Please pull the latest image from Docker hub and see if the issue is fixed for you.

**Comment by sofauxboho** [comment] 2024-03-02 16:37
Gotcha, thanks for the response and potential resolution.

I caught the section name change during my earlier troubleshooting and did change that manually, but again I had been monkeying with other aspects as well so it wasn't a good test. I have updated to v0.0.70 and am running scsd manually in the Docker image's console now, it is working. After it finishes I'll wait for it to be run by the scheduler, find the log file, and update here with the result.

**Comment by sofauxboho** [comment] 2024-03-02 20:47
As above, I updated to v0.0.70 and ran scsd manually from the Docker image's console. It ran normally, downloaded / updated files successfully. I double checked that /user/data and /user/data/scsd.log did not exist (they did not). Then I closed the image console and waited.

Opening the console again now, /user/data/scsd.log does now exist and contains this: 
![image](https://github.com/pyscsd/steamCloudSaveDownloader/assets/418438/89c51734-47db-4d49-b41c-7d20263ef37e)

Still running with default settings, as confirmed here: 
![image](https://github.com/pyscsd/steamCloudSaveDownloader/assets/418438/50c57529-0ed8-4026-aeb3-185d1595aef5)

So: In v0.0.70 with default settings the scsd Docker image uses /data/ for its data directory when run manually but uses /user/data/ for its data directory when run by the scheduler.

**Comment by hhhhhojeihsu** [comment] 2024-03-03 02:05
It seems like the config file used is the one generated by old version. Hence the `[Required]` section in `scsd.conf.default`. Please make sure that:
- The docker image used is the latest one (sha: 222dc4) with v0.0.70
- Either delete the `scsd.conf.default` to let the script regenerate one automatically, or manual change the section name to `[General]`

**Comment by sofauxboho** [comment] 2024-03-06 20:20
Deleted everything again and set up fresh with v0.0.70, confirmed correct sha. Let it generate a default .conf and authenticated.

It ran correctly when run manually, but each time it was run by the scheduler I got:

> 2024-03-06 00:39:00 [INFO] scsd-0.0.70 started
> 2024-03-06 00:39:00 [INFO] Files will be saved to '/data'
> 2024-03-06 00:39:00 [INFO] Refreshing session
> 2024-03-06 00:39:03 [INFO] Getting Game Save List
> 2024-03-06 00:39:03 [INFO] Random sleep for 4 seconds
> 2024-03-06 00:39:08 [INFO] (1/171) Processing Steam Client
> 2024-03-06 00:39:08 [INFO] Random sleep for 4 seconds
> 2024-03-06 00:39:13 [ERROR] Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/steamCloudSaveDownloader/__main__.py", line 93, in __main__
>     main(parsed_args, notifier_)
>   File "/usr/lib/python3.10/site-packages/steamCloudSaveDownloader/__main__.py", line 270, in main
>     update_game(db_, storage_, web_, game, summary_)
>   File "/usr/lib/python3.10/site-packages/steamCloudSaveDownloader/__main__.py", line 213, in update_game
>     db_.add_requests_count(requests_count)
>   File "/usr/lib/python3.10/site-packages/steamCloudSaveDownloader/db.py", line 129, in add_requests_count
>     res = cur.execute("UPDATE REQUESTS SET num = ?, time = ? WHERE id = 0;", (count, now))
> sqlite3.OperationalError: attempt to write a readonly database

I lazily ran:
```
chmod 777 sessions.sb
chmod 777 scsd.sqlite3
```

And it seems to be working correctly now. When invoked by the scheduler scsd runs correctly and files are downloaded / updated. 

Not sure why ownership / access to those files was funny in the Docker image.

I'll re-enable my Discord webhook now, but I think I'm set. Thanks again!

**Comment by hhhhhojeihsu** [comment] 2024-03-10 14:43
The permission issue might be related to the permission of parent folder or UMASK. I'll add more error handling to that in the future. For now please let me know if the main problem described is fixed so I can close this issue. Thanks.

**Comment by sofauxboho** [comment] 2024-03-15 17:21
Yup, confirming the main problem previously described is fixed and scsd is running successfully with the scheduler now. 

Thanks for all the help.

**Closed** 2024-03-16 03:51 UTC
Labels: bug, documentation
